# .github/workflows/coverage.yml
name: Test Coverage
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Your original steps
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-node@v6
      - name: Install
        run: npm install
      - name: Test and Coverage
        run: npm run 'test:cov'

      - name: Create Coverage Badges
        uses: jaywcjlove/coverage-badges-cli@main
        with:
          style: flat
          source: coverage/coverage-summary.json
          output: coverage/badges.svg
          jsonPath: totals.percent_covered

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./badges